# Generated by Django 2.2 on 2019-04-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('photo', models.FilePathField()),
                ('material', models.CharField(choices=[('cotton', 'хлопок'), ('polyamide', 'полиамиды'), ('wool', 'шерсть'), ('polyester', 'полиэстеры')], max_length=10)),
                ('cost', models.PositiveSmallIntegerField()),
                ('size', models.CharField(choices=[('one', 'один размер'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL')], max_length=11)),
                ('gender', models.CharField(choices=[('men', 'мужчинам'), ('women', 'женщинам'), ('kids', 'детям')], max_length=8)),
                ('category', models.CharField(choices=[('shirts', 'рубашки'), ('coats', 'пальто и куртки'), ('sweatshirts', 'толстовки'), ('knitwear', 'трикотаж'), ('tshirts', 'футболки'), ('trousers', 'щтаны'), ('shorts', 'шорты'), ('accessories', 'аксессуары')], max_length=15)),
            ],
        ),
    ]
