# Generated by Django 2.2 on 2019-04-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_auto_20190417_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='item',
            name='material',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
    ]
