# Generated by Django 2.2 on 2019-04-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_auto_20190417_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.FilePathField(default=''),
        ),
    ]
