# Generated by Django 2.2 on 2019-04-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_auto_20190417_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo',
        ),
    ]
