# Generated by Django 2.2 on 2019-04-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_remove_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.FileField(null=True, upload_to='item_photo'),
        ),
    ]
