# Generated by Django 2.2 on 2019-04-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(choices=[('cotton', 'хлопок'), ('polyamide', 'полиамиды'), ('wool', 'шерсть'), ('polyester', 'полиэстеры')], default='cotton', max_length=10),
        ),
    ]
