# Generated by Django 2.2 on 2019-04-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0009_item_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('shirts', 'рубашки'), ('coats', 'пальто и куртки'), ('sweatshirts', 'толстовки'), ('knitwear', 'трикотаж'), ('tshirts', 'футболки'), ('trousers', 'щтаны'), ('shorts', 'шорты'), ('accessories', 'аксессуары')], default='shirts', max_length=15),
        ),
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('men', 'мужчинам'), ('women', 'женщинам'), ('kids', 'детям')], default='men', max_length=8),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('one', 'один размер'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL')], default='xs', max_length=11),
        ),
    ]
