# Generated by Django 2.1.7 on 2019-04-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_auto_20190418_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cost',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
