# Generated by Django 2.1.7 on 2019-04-20 15:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0014_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('shirts', 'рубашки'), ('coats', 'пальто и куртки'), ('sweatshirts', 'толстовки'), ('knitwear', 'трикотаж'), ('tshirts', 'футболки'), ('trousers', 'штаны'), ('shorts', 'шорты'), ('accessories', 'аксессуары')], default='shirts', max_length=15, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('men', 'мужчинам'), ('women', 'женщинам'), ('kids', 'детям')], default='men', max_length=8, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(choices=[('cotton', 'хлопок'), ('polyamide', 'полиамиды'), ('wool', 'шерсть'), ('polyester', 'полиэстеры')], default='cotton', max_length=10, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.FileField(null=True, upload_to='item_photo', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('one', 'один размер'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL')], default='xs', max_length=11, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Идентификатор'),
        ),
    ]
