# Generated by Django 2.1.7 on 2019-04-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0015_auto_20190420_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
    ]
