# Generated by Django 2.1.7 on 2019-04-20 15:59

import clothes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0016_item_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/media/item_photos/item_no_image.png', upload_to=clothes.models.image_folder, verbose_name='Изображение'),
        ),
    ]
