# Generated by Django 2.1.7 on 2019-04-20 16:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0017_auto_20190420_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(choices=[('cotton', 'хлопок'), ('polyamide', 'полиамиды'), ('wool', 'шерсть'), ('polyester', 'полиэстеры')], default='cotton', max_length=10, null=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Стоимость'),
        ),
    ]
