# Generated by Django 2.1.7 on 2019-04-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0018_auto_20190420_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
