# Generated by Django 2.1.7 on 2019-04-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0020_auto_20190420_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[(None, ''), ('shirts', 'рубашки'), ('coats', 'пальто и куртки'), ('sweatshirts', 'толстовки'), ('knitwear', 'трикотаж'), ('tshirts', 'футболки'), ('trousers', 'штаны'), ('shorts', 'шорты'), ('accessories', 'аксессуары')], default=None, max_length=15, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[(None, ''), ('men', 'мужчинам'), ('women', 'женщинам'), ('unisex', 'unisex'), ('kids', 'детям')], default='men', max_length=8, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(choices=[(None, ''), ('cotton', 'хлопок'), ('polyamide', 'полиамиды'), ('wool', 'шерсть'), ('polyester', 'полиэстеры')], default=None, max_length=10, null=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[(None, ''), ('one', 'Один размер'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('3xl', '3XL')], default='xs', max_length=11, null=True, verbose_name='Размер'),
        ),
    ]
