# Generated by Django 2.1.7 on 2019-04-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0022_auto_20190420_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[(None, ''), ('shirts', 'рубашки'), ('coats', 'пальто и куртки'), ('sweatshirts', 'толстовки'), ('knitwear', 'трикотаж'), ('tshirts', 'футболки'), ('trousers', 'штаны'), ('shorts', 'шорты'), ('accessories', 'аксессуары'), ('misc', 'разное')], default=None, max_length=15, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, ''), ('men', 'мужчинам'), ('women', 'женщинам'), ('unisex', 'unisex'), ('kids', 'детям')], default=None, max_length=8, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[(None, ''), ('one', 'Один размер'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('3xl', '3XL')], default='m', max_length=11, null=True, verbose_name='Размер'),
        ),
    ]
