# Generated by Django 2.1.7 on 2019-04-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0023_auto_20190420_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, choices=[(None, ''), ('cotton', 'хлопок'), ('polyamide', 'полиамиды'), ('wool', 'шерсть'), ('polyester', 'полиэстеры')], default=None, max_length=10, null=True, verbose_name='Материал'),
        ),
    ]
